[package]
name = "boggle-maker"
version = "0.1.3"
edition = "2024"
description = "Rust tools for Boggle enthusiasts: board generation and word analysis."
license = "MIT OR Apache-2.0"

[dependencies]
genetic_algorithm = "0.18.1"
rand = "0.9.0"
word-trie = "0.1.0"
